# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: business.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'business.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62usiness.proto\x12\x08\x62usiness\"\x1f\n\x0f\x42usinessRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"#\n\x10\x42usinessResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x91\x02\n\x0f\x42usinessService\x12\x41\n\x06\x43reate\x12\x19.business.BusinessRequest\x1a\x1a.business.BusinessResponse\"\x00\x12\x39\n\x03Get\x12\x14.business.GetRequest\x1a\x1a.business.BusinessResponse\"\x00\x12?\n\x06Update\x12\x17.business.UpdateRequest\x1a\x1a.business.BusinessResponse\"\x00\x12?\n\x06\x44\x65lete\x12\x17.business.DeleteRequest\x1a\x1a.business.BusinessResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'business_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUSINESSREQUEST']._serialized_start=28
  _globals['_BUSINESSREQUEST']._serialized_end=59
  _globals['_GETREQUEST']._serialized_start=61
  _globals['_GETREQUEST']._serialized_end=85
  _globals['_UPDATEREQUEST']._serialized_start=87
  _globals['_UPDATEREQUEST']._serialized_end=128
  _globals['_DELETEREQUEST']._serialized_start=130
  _globals['_DELETEREQUEST']._serialized_end=157
  _globals['_BUSINESSRESPONSE']._serialized_start=159
  _globals['_BUSINESSRESPONSE']._serialized_end=194
  _globals['_BUSINESSSERVICE']._serialized_start=197
  _globals['_BUSINESSSERVICE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
