apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-servicemonitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: flask-app
  endpoints:
  - port: metrics
    path: /metrics
    scheme: http
    interval: 15s
    targetPort: 5000
